### ISSUE TITLE
Rails 4.2.3  - undefined local variable or method `environment' 

### ISSUE THREAD

**Issue by oristian** [frmendes/rails-template-cache#1]
undefined local variable or method `environment' for #Object:0x007ff23ddddec0
  (in /Users/mike/code/cpw/vendor/bundle/gems/rails-template-cache-0.1.1/app/assets/javascripts/rails-template-cache/rails-template-cache.js.erb)
Extracted source (around line #6):

``` ruby
  angular.module('templates', []).run(['$templateCache', function($templateCache) {
    <%
      environment.context_class.instance_eval { include ActionView::Helpers::JavaScriptHelper }
      app_root  = File.expand_path('../../', __FILE__)
      templates = File.join(app_root, %w{templates ** *.html})
```

**Comment by frm** [comment]
@mosofoco what version of the gem are you using? 0.1.1?

**Comment by oristian** [comment]
@frmendes yep 0.1.1.

**Comment by frm** [comment]
@mosofoco Do you have sprockets-rails in your bundle? I think I missed that in the gemspec file.

**Comment by frm** [comment]
@mosofoco I'm not able to reproduce the problem. Any news?
